### ISSUE TITLE
Cache aren't invalidated

### ISSUE THREAD

**Issue by jante-knowit** [episerver/content-events-masstransit#5]
We are trying to implement cache invalidation on a load balanced environment, but can't get it to work.
RabbitMQ has been installed and we can see that there are messages beings sent when we publish a page on one of the sites. The messages contain the correct Content- and Version-id and are being received by the consuming site but the cache isn't invalidated. I'm not sure where to begin troubleshoot, any help would be appreciated.

**Comment by lunchin** [comment]
Okay, the cache invalidation should happen after the message is consumed by the framework.  Let me see If I can recreate

**Comment by lunchin** [comment]
Can you try 1.0.0--pre-42, I had to manually raise the event locally when consuming the message.  Seems to work in the test I ran.

**Comment by jante-knowit** [comment]
Installed 1.0.0--pre-42, and now the invalidation seems to work as it should. Thanks!
